# The expected input image height and width of the images from CVAT.
cvat_image_shape_phantom: [3648, 5472]  # Phantom 4 images
cvat_image_shape_phantom_video: [1520, 2704]  # Phantom 4 video
# This is the shape that we will try to coerce the resulting patches to. It
# will not change the aspect ratio, so this may involve cropping.
coerced_patch_shape: [432, 576]

# The scale factor to apply for the patches we extract.
annotation_patch_scale: 0.25
# The stride of the patches to extract, in frame fractions.
annotation_patch_stride: 0.25

# How many images from the start that we want to skip annotating.
num_initial_frames_to_skip: 250
# Total number of images that we want to annotate.
num_frames_to_annotate: 40
# How many frames to skip between each annotated one. This can be useful
# for videos with many consecutive similar frames.
annotation_interval: 30
