# The scale factor to apply for the patches we extract.
patch_scale: 0.125
# Number of scales to use when computing the loss.
num_loss_scales: 3

# Frequency at which to generate histograms for Tensorboard output.
histogram_frequency: 1
# Number of training epochs after which to rebalance the dataset.
rebalance_frequency: 100
# Every time this many epochs elapse, it will generate new density map visualizations.
visualization_period: 10
# How many images from each batch to visualize.
num_per_batch_to_visualize: 1
# Maximum number of testing batches to visualize data from.
max_num_batches_to_visualize: 20

# Focal loss parameters.
focal_loss_alpha: 0.75
focal_loss_gamma: 2.0

# Whether to enable debugging checks for NaN and infinity. This
# is very useful when trying to debug numerical issues, but it
# slows down training a lot.
enable_numeric_checks: false

# Learning phases to use for training the model.
learning_phases:
  # The initial learning rate to use for the phase.
  - learning_rate:
      # Initial learning rate value.
      initial: 0.005
      # Specify that we want to decay over time.
      decay: true
      # Number of steps to decay over.
      # (1822 steps per epoch)
      decay_steps: 9110
      # Used to derive the number of iterations in the i-th period.
      t_mul: 2.0
      # Used to derive the initial learning rate of the i-th period.
      m_mul: 1.0
      # Minimum learning rate to hit.
      min_learning_rate: 0.000005
    # The momentum to use for the phase.
    momentum: 0.9
    # Number of epochs to train for in this phase.
    num_epochs: 35

    # The loss weight to use for the PAC.
    pac_loss_weight: 1.0
    # The weight to use for the combined BCE loss.
    combined_bce_loss_weight: 0.2
    # The weight to use for the scale consistency loss.
    scale_consistency_loss_weight: 0.002
