# The scale factor to apply for the patches we extract.
patch_scale: 0.125

# Frequency at which to generate histograms for Tensorboard output.
histogram_frequency: 1
# Every time this many epochs elapse, it will generate new density map visualizations.
visualization_period: 6

# A list of the minimum count values that will go in each discrete
# count bucket. Note that the highest bucket will contain anything
# that falls between the largest minimum value and infinity.
bucket_min_values: [0.0, 1.0]

# Learning phases to use for training the model.
learning_phases:
  # The initial learning rate to use for the phase.
  - learning_rate:
      # Initial learning rate value.
      initial: 0.01
      # Specify that we want to decay over time.
      decay: true
      # Number of steps to decay over.
      # (628 steps per epoch)
      decay_steps: 1884
      # Used to derive the number of iterations in the i-th period.
      t_mul: 2.0
      # Used to derive the initial learning rate of the i-th period.
      m_mul: 1.0
      # Minimum learning rate to hit.
      min_learning_rate: 0.00001
    # The momentum to use for the phase.
    momentum: 0.9
    # The loss weight for density maps.
    density_map_loss_weight: 0.0
    # The loss weight for count regression.
    count_loss_weight: 0.0
    # The loss weight for count categorization.
    discrete_count_loss_weight: 1.0
    # Number of epochs to train for in this phase.
    num_epochs: 45
