# The expected input image dimensions.
input_width: 4608
input_height: 3456
# The scale factor to apply for the patches we extract.
patch_scale: 0.25

# The shape of the density maps to use.
# (These are derived from the expected input dimensions, down-sampled by a factor of 8).
density_map_width: 576
density_map_height: 432
# The standard deviation to use for the gaussian kernel when creating density maps.
density_map_sigma: 1

# Batch size to use for training.
batch_size: 10
# Number of batches to pre-fetch into memory.
# (Increasing this can increase training performance at the expense of memory usage.)
num_prefetch_batches: 10

# Defines different learning phases to carry out.
learning_phases:
  # The initial learning rate to use for the phase.
  - learning_rate: 0.0001
    # The momentum to use for the phase.
    momentum: 0.9
    # The loss weight for density maps.
    density_map_loss_weight: 1.0
    # The loss weight for counts.
    count_loss_weight: 0.0
    # Number of epochs to train for in this phase.
    num_epochs: 100
