# This is a boilerplate parameters config generated for pipeline 'annotation_reupload'
# using Kedro 0.16.4.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/stable/04_kedro_project_setup/02_configuration.html#parameters
