# SAM model parameters.
sam_model_type: "vit_h"
#sam_weights_file: "/blue/cli2/daniel.petti/aerial_flower/data/06_models/sam_vit_h_4b8939.pth"
sam_weights_file: "data/06_models/sam_vit_h_4b8939.pth"

# Image size to use for inference. (h, w)
inference_size: [1377, 484]

# Date on which the field was planted.
field_planted_date: 2021-06-18
# Number of plots that failed to germinate.
num_empty_plots: 286
# When we see this fraction of the total flowers, we will consider this
# the start of flowering.
flower_start_threshold: 0.05
# When we see this fraction of the total flowers, we will consider this
# the end of flowering.
flower_end_threshold: 0.95

# GSDs to use for each session.
session_gsds:
  # Phantom 4 sessions.
  "2021-08-09": 0.27

  "2021-08-13": 0.27
  "2021-08-16": 0.27
  "2021-08-20": 0.27
  "2021-10-08": 0.27

  # M100 sessions.
  "2021-08-27": 0.23
  "2021-08-30": 0.23
  "2021-09-03": 0.23
  "2021-09-06": 0.23
  "2021-09-10": 0.23
  "2021-09-13": 0.23
  "2021-09-17": 0.23
  "2021-09-24": 0.23
  "2021-09-27": 0.23
  "2021-10-01": 0.23
  "2021-10-11": 0.23
  "2021-10-15": 0.23
  "2021-10-18": 0.23
  "2021-10-22": 0.23
  "2021-10-25": 0.23
  "2021-10-29": 0.23
  "2021-11-01": 0.23
  "2021-11-05": 0.23
  "2021-12-13": 0.23
