# Location where the detection model weights are saved.
model_weights_file: "yolov8m_flower_active_7.pt"

# Batch size to use for inference.
prediction_batch_size: 16

# Minimum confidence we allow for flower detections.
min_confidence: 0.25

# Whether to do a try run without running the detector.
dry_run: false