# Locations where the detection model weights are saved.
flower_model_weights_file: "yolov8m_flower_active_9.pt"
boll_model_weights_file: "data/06_models/dm_count/best_model_6.pth"

# Batch size to use for inference.
prediction_batch_size: 16

# Minimum confidence we allow for flower detections.
min_confidence: 0.5

# Whether to do a try run without running the detector.
dry_run: false
