# Number of batches to pre-fetch into memory.
# (Increasing this can increase training performance at the expense of memory usage.)
num_prefetch_batches: 10

# Whether we want to classify counts instead of regressing them.
classify_counts: True
# Batch size to use for training.
batch_size: 16
