# The patch scale factor that we will use for generating density maps.
eval_patch_scale: 0.5
# The patch stride that we will use for generating density maps.
eval_patch_stride: 0.5
# Batch size to use for evaluation.
eval_batch_size: 8
