# Date on which the field was planted.
#v2_field_planted_date: 2023-05-19
v2_field_planted_date: 2024-05-30
# Last effective flower date to use for analysis. Flowers that open later than
# this date will be assumed not to develop into bolls.
#last_effective_flower_date: 2023-09-15
last_effective_flower_date: 2024-09-15

# Number of genotypes we want to collect from the field.
num_genotypes_to_collect: 75
# Quantile ranges that define the early and late flowering habits.
early_late_quantiles: [0.2, 0.85]
# Quantile range that defines the optimal flowering habit.
optimal_quantile_range: 0.05

# Excess green threshold to use for eliminating plots with poor germination.
# The excess green values are normalized on a scale from 0-10.
excess_green_threshold: 2
