# Date on which the field was planted.
v2_field_planted_date: 2023-05-19

# Number of genotypes we want to collect from the field.
num_genotypes_to_collect: 40
# Quantile ranges that define the early and late flowering habits.
early_late_quantiles: [0.05, 0.95]
# Quantile range that defines the optimal flowering habit.
optimal_quantile_range: 0.025
